version: '3'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cli:
    build:
      context: .
      dockerfile: Dockerfile.cli

    environment:
      - POSTGRES_HOST=db
      - "POSTGRES_PORT=${POSTGRES_PORT}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"

    depends_on:
      - db

    command: /bin/sh -c "pipenv run create && pipenv run migrate
              && pipenv run seed"


volumes:
  postgres_data:
