FROM python:3.10-slim-buster

WORKDIR /app

COPY ./Pipfile ./
COPY ./config.py ./
COPY ./db_scripts ./db_scripts
COPY ./src/cli ./app/cli
COPY ./src/core  ./app/core
COPY ./src/__init__.py  ./app/
COPY ./alembic.ini  ./


RUN apt-get update && apt-get install -y gcc libpq-dev && apt-get clean
RUN pip install pipenv
RUN pipenv install --deploy


ENTRYPOINT ["pipenv", "run", "python", "-m", "src.cli"]

