"""sqlalchemy migration2

Revision ID: 018e737e805b
Revises: 6ae2d691f0ad
Create Date: 2023-10-18 10:49:52.461700

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "018e737e805b"
down_revision: Union[str, None] = "6ae2d691f0ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
