"""initial migration

Revision ID: 4c53d87630fe
Revises: 
Create Date: 2023-10-16 13:36:37.203663

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c53d87630fe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS devicestatus;")
    op.execute("DROP TYPE IF EXISTS devicetype;")

    op.create_table(
        "electronicdevice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, unique=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ON", "OFF", name="devicestatus"),
            nullable=False,
            server_default="OFF",
        ),
        sa.Column(
            "type",
            sa.Enum("TV", "MICROWAVE", "AIRCONDITIONER", "OTHER", name="devicetype"),
            nullable=False,
            server_default="OTHER",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "airconditioner",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("degrees", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["electronicdevice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "microwave",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("degrees", sa.Integer(), nullable=False),
        sa.Column("timer", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["electronicdevice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tv",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["electronicdevice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
