"""sqlalchemy migration2dsfsd

Revision ID: 603a9e8bb603
Revises: beb118a14b53
Create Date: 2023-10-19 18:22:21.340565

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "603a9e8bb603"
down_revision: Union[str, None] = "beb118a14b53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
