"""sqlalchemy migration2220

Revision ID: beb118a14b53
Revises: 21a9cd69592a
Create Date: 2023-10-18 17:29:37.905075

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "beb118a14b53"
down_revision: Union[str, None] = "21a9cd69592a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
