"""initial migration

Revision ID: 05f466fb9660
Revises: 4c53d87630fe
Create Date: 2023-10-16 13:38:44.275744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW




# revision identifiers, used by Alembic.
revision: str = '05f466fb9660'
down_revision: Union[str, None] = '4c53d87630fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
